version: '3.5'

services:
  db:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: db.dockernet
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.12.10-management-alpine
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=qwesda
    volumes:
      - ./docker/config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  node-red-data: